name: Build static

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
        
defaults:
  run:
    working-directory: static/annoto

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [
          14.x,
          16.x
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test:e2e:ci
      - run: npm run test:unit:ci
